language: node_js

node_js:
  - "8.6.0"

services:
  postgresql

addons:
  postgresql: "6.4"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml