# version: "1"
# services:
#   web:
#     image:
#     deploy:
#     replicas: 0
#     restart_policy:
#         condition: on-failure
#       resources:
#         limits:
#           cpus: "0.1"
#           memory: 50M