version: "3.3"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: nehacp/mixtape
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOSTNAME=mixtape-db.c3n2ec9z6jqb.us-east-2.rds.amazonaws.com
      - DB_NAME=mixtape
      - INDEX=mixtape
      - DB_USER=mixtapedb
      - DB_PASSWORD=mixtapedb
      - PORT=3000
      - AWS_ACCESS_KEY_ID=AKIAIL27LUBNNYKEK7LA
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=us-east-2
      - AWS_URL=https://sqs.us-east-2.amazonaws.com/215259879748/mixtape-user-interactions
    networks:
      - webnet
networks:
  webnet: